### ISSUE TITLE
Gitlab konverterar projektnamn till lowercase

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#3]
Eftersom Gitlab skapar projektnamn i lowercase. Detta betyder att vi inte kan utgå ifrån att Emu-databasen som root-bibliotek i Gitlab. MittProjekt_emuDB kommer alltså att bli mittprojekt_emudb när Gitlab lägger upp det, och det kommer inte Emu att se som en databas.

Jag föreslår därför att hela projektbiblioteket ligger i Gitlab

```
Mitt_projekt/  # <- Root i Gitlab-projektet
Mitt_projekt/Data
Mitt_projekt/Data/MittProjekt_emuDB # <- Biblioteket som EmuR kopplar upp sig mot för att göra analyser
Mitt_projekt/Dokument/
Mitt_projekt/Resultat/
```
Det betyder också att EMU-webApp måste push:a till `Mitt_projekt/Data/MittProjekt_emuDB`.

**Comment by johanvonboer** [comment]
Fixat.

Mapp-struktur är skapad enligt:
https://github.com/humlab-speech/humlab-speech-deployment/issues/18

Och EMU-webApp är patchad till att stödja att man skickar in git repo subdir som argument, har även skapat en pull request för detta i original-repot: https://github.com/IPS-LMU/EMU-webApp/pull/292
