### ISSUE TITLE
The OCTRA setup may be missing parts?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#34]
The installation of OCRTA that we have now does not take keyboard input in the 2d editor, and switching to a different editor takes a long time (most often it stalls).

**Comment by TomasSkotare** [comment]
As far as I can tell, the issues have been resolved. Can you verify the current version @FredrikKarlssonSpeech ?

**Comment by FredrikKarlssonSpeech** [comment]
As far as I can tell, it works as expected. I have also asked @liasam92 to try it out so find issues I cannot see.

**Comment by liasam92** [comment]
German is the default language when a user (not logged in) opens OCTRA
