### ISSUE TITLE
Load Reindeer instead of EMU

### ISSUE THREAD

**Issue by johanvonboer** [humlab-speech/humlab-speech-deployment#36]
In RStudio/Jupyter

**Comment by FredrikKarlssonSpeech** [comment]
Related to this is that Praat and superassp then also need to be available.

**Comment by FredrikKarlssonSpeech** [comment]
LIbraries that should be installed per default (including dependencies)

tidyverse
tidymodels (not sure that they all are also part of the tidyverse meta package)
reindeer
superassp

**Comment by FredrikKarlssonSpeech** [comment]
Sorry, for got that it is probably a good idea to have

openxlsx
ggpubr 

too.

**Comment by FredrikKarlssonSpeech** [comment]
Duplicate
