### ISSUE TITLE
The Rstudio and Jupiter R environments should be the same

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#40]
I guess that the most sensible way to do this is to set up all projects as packrat 

https://rstudio.github.io/packrat/

projects by default. This, I suspect, means that all standard packages will have to be installed into the packrat repo when the project is created, which could be a source of some delay. But, then all projects will be self-contained and the code / analyses reproducible by default, so I guess that could be worth the effort?

**Comment by johanvonboer** [comment]
Will look into this. We would have to do it as a pre-made template directory that is just being copied in, since installing packrat + all the things we want, such as emuR, would take way too long (several minutes). But I agree that packrat definitely seems very cool for all the reasons you mention...

**Comment by FredrikKarlssonSpeech** [comment]
I agree. A pre-made default directory/environment has several advantages, and if we make all newly created projects packrat enabled, then nothing breaks for a project if we decide to make a change in the versions of libraries that we offer (which may have consequences that we did not foresee).

I am all for a new project skeleton being just copied in as the basis for our structure.

**Comment by FredrikKarlssonSpeech** [comment]
![Skärmavbild 2021-05-06 kl  13 02 44](https://user-images.githubusercontent.com/200246/117288330-aa7d3c80-ae6b-11eb-9c45-f76e5a7bc312.png)

I know that we all know this has not been put in place yet, but just to illustrate the issue :-)
