### ISSUE TITLE
Default annotation level links should be added when creating a new project

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/humlab-speech-deployment#51]
When creating a new project there are default annotation levels (Word and Phonetic). 
The links between them (level links) should also be set on default:

![Skärmavbild 2021-05-03 kl  11 46 15](https://user-images.githubusercontent.com/63298177/116862765-88828080-ac05-11eb-89b8-57afb2dc361f.png)

Like this:
![Skärmavbild 2021-05-03 kl  11 49 47](https://user-images.githubusercontent.com/63298177/116862908-c1baf080-ac05-11eb-81a7-a50fd23c0361.png)

If possible, the level link should be deleted if any of the default levels (Word or Phonetic) is deleted

**Comment by johanvonboer** [comment]
Fixed
