### ISSUE TITLE
Tooltips when creating a new project

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/humlab-speech-deployment#54]
Suggestions:
**Documentation**
 Upload your project documents (e.g., ethical approval, data management plan, project application). The documents are stored in the _Documents_ folder on your project server
    
**Create an EmuDB database**
  An EmuDB is required to work with the EMU tools (e.g., EmuWebApp for transcription, Emu-R for analyses). You should only uncheck this box if you really know what you are doing. Your EmuDB is stored in the _Data_ folder on your project server.
    
**Sessions**
 Use 'Sessions’ to organise your recordings. You may, for example, group all recordings from a speaker in one session or have multiple sessions per speaker in the case of longitudinal data collection. It is entirely up to you to decide how to organise your recordings, but the way you choose to organise your files may facilitate later analysis.

**Annotation structure**
 Here, you define the annotation levels and their relationship to one another. The default structure is _Word_ and _Phonetics_, and their relationship is one-to-many, meaning that one word may consist of several phonemes. An annotation level can be of type ITEM, SEGMENT or EVENT. An ITEM level is timeless and contains labels only. A SEGMENT level has a start time and a duration. An EVENT level contains a single time point only. In the standard case, _Phonetics_ have a label, a start time and a duration, while _Words_ only contain labels. You may add or remove annotations levels. If you do, make sure you also add/remove the links between them.

**Comment by liasam92** [comment]
**Sessions**
'Sessions’ are used to group all recordings from a speaker.  If you are collecting longitudinal data, we recommend that you add a new `session` for each recording session.

**Session metadata**
Metadata contain important information about your audio files. Speakers' age and gender are used to calculate formant tracks, but you may also add other types of metadata (e.g., participant id, treatment condition, follow-up date, etc.). Metadata helps you organise your data and may facilitate later analysis.

**Comment by liasam92** [comment]
and I see that I have written _Phonetics_, should be _Phonetic_ (I think)

**Comment by johanvonboer** [comment]
Added to the webclient
