### ISSUE TITLE
An ability to create and edit a project 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#6]
* Set a name
* Get / (Set?) a computer friendly name of the project, that is also used as the name of the base folder of the project
* The ability to add a EPM approval, 
* * or a checkbox stating that the source material is not sensitive and has been collected within a project within Umeå university. 
*

**Comment by johanvonboer** [comment]
I think we decided on the last meeting that this was pretty much done?
