### ISSUE TITLE
Store Age and Gender for a session

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#69]
When we store a session, we store age and gender of the speaker as a 

SESSION_NAME.meta_json

which may then contain 

[{"Gender":"Male","Age":32}]

The JSON file is stored in the session directory.

**Comment by FredrikKarlssonSpeech** [comment]
That is,

THe session

0000_ses/0000.meta_json

**Comment by johanvonboer** [comment]
Is there a reason to why this is stored as a single object in an array? Or could we strip the array and just store it like `{"Gender":"Male","Age":32}` ?

**Comment by johanvonboer** [comment]
Also - and this is very minor - but I'm thinking it might be best to let the age field also be a string, in case people want to write something like "N/A" or "not disclosed" or "estimated 25-30" etc. Just thinking that the real world is a messy place and it's good to have data formats which are flexible enough to allow for it, or what do you think?

**Comment by johanvonboer** [comment]
This is now implemented
