### ISSUE TITLE
The ability to create a personal project for testing and teaching

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#7]
* Named according to the SWAMID of the person 
* Setup of the base folders
* The ae Emu database is automatically created and linked in the standard way (by the .Rprofile)

* An ability to reset the personal project

**Comment by johanvonboer** [comment]
These things are more or less implemented (although perhaps not exactly as specified), e.g. a 'reset' of a project can be done by just deleting it and creating a new one.
