### ISSUE TITLE
Get annotation levels to show in Emu-webApp main view

### ISSUE THREAD

**Issue by liasam92** [humlab-speech/humlab-speech-deployment#71]
The only way that I have managed to get annotation levels to show in the main view is by code:
`set_levelCanvasesOrder(dbHandle, perspectiveName = "default", order = c("Phonetic"))`

However, we need a smarter function here to add the order.
Users may add several annotation levels of type `segment` and `event`, and these should all be visible in the main view.
So the function `order = c("Phonetic"))` needs to be dynamic, with segments first and events last in order

**Comment by johanvonboer** [comment]
Ready for testing
