### ISSUE TITLE
Standardized set up of a project

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#8]
* Standardized folder structure
* Makes it possible to transcribe (EMU-webApp) material in the project
* Create or open Jypyter notebooks in the project
-- R core 
* Loading of .Rprofile when jypyter is loaded
- which in turn loads eloquent.researcher package
-- And sets up standardized database handles for the emu database
- and the EmuR package
* Go into Rstudio instead
-- Again, loading .Rprofile to set everything up correctly

**Comment by johanvonboer** [comment]
I think we can consider these 2 things to be done? If not we'll just open new issues for them...
> Makes it possible to transcribe (EMU-webApp) material in the project

> Create or open Jypyter notebooks in the project

And I have split the remaining tasks into multiple issues:

Standardized folder structure:
https://github.com/humlab-speech/humlab-speech-deployment/issues/18

Loading of .Rprofile when jypyter is loaded:
https://github.com/humlab-speech/humlab-speech-deployment/issues/19

So I'm closing this one.
